[package]
name = "satrs-example"
version = "0.1.0"
edition = "2021"
authors = ["Robin Mueller <muellerr@irs.uni-stuttgart.de>"]
default-run = "satrs-example"

[dependencies]
fern = "0.6"
chrono = "0.4"
log = "0.4"
crossbeam-channel = "0.5"
delegate = "0.10"
zerocopy = "0.6"
csv = "1"
num_enum = "0.6"
thiserror = "1"
embedded-can = "0.4"
#socketcan = "2.0"
derive-new = "0.5"
num-traits = "0.2"
num-derive = "0.3"

[dependencies.satrs-core]
path = "../satrs-core"

[dependencies.satrs-mib]
path = "../satrs-mib"


